const SPOILER_WORDS_LIST_POLITICS = [
    "Ram Nath Kovind",
    "Narendra Modi",
    "Modi",
    "Rahul Gandhi",
    "Indira Gandhi",
    "Rajiv Gandhi",
    "Sonia Gandhi",
    "Priyanka Gandhi",
    "Robert Vadra",
    "Mamta Banerjee",
    "Pappu",
    "Lalu Prasad Yadav",
    "Lalu",
    "Arvind Kejriwal",
    "Kejriwal",
    "Amit shah",
    "mayawati",
    "jawaharlal nehru",
    "nehru",
    "akhilesh yadav",
    "mulayam",
    "manmohan singh",
    "nitish kumar",
    "arun jaitley",
    "jaitley",
    "jayalalithaa",
    "atal bihari vajpayee",
    "vajpayee",
    "atal",
    "sharad pawar",
    "sushma swaraj",
    "deve gowda",
    "paswan",
    "chandrababu",
    "nitin gadkari",
    "pranab mukherjee",
    "yogi adityanath",
    "yogi",
    "advani",
    "smriti irani",
    "shashi tharoor",
    "thackeray",
    "Congress",
    "AAM aadmi party",
    "dmk",
    "shivsena",
    "Samajwadi Party"
    ];

console.log(JSON.stringify(SPOILER_WORDS_LIST_POLITICS));

